version: '3.7'
services: 
  backend:
    restart: always
    build:
      context: .
#    depends_on:
#      - database
    container_name: 'bidside-backend'
    command: "pm2-runtime ecosystem.config.js"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - jwtSecret=supersecret
      - mongodbUser=rendszerf
      - mongodbPswd=cBiuMYANMuMgv8H9
