version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            echo "Let's start copy"
            ls -la
            scp -r ./* root@139.162.143.192:deploy/
            echo "Copy finished"
      - run:
          name: Start docker
          command: |
            ssh root@139.162.143.192 "cd deploy && docker-compose down && docker-compose up -d"

workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master # only deploy on the master branch
